global using HQTestClient.Infrastructure.Clients;
global using HQTestClient.Infrastructure.Connectors;
global using HQTestClient.Infrastructure.Interfaces;
global using Binance.Spot;
global using HQTestClient.Infrastructure.Hubs;
global using HQTestClient.Infrastructure.Services;
global using Microsoft.AspNetCore.SignalR;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.RazorPages;